openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: AWS Elemental MediaPackage Channels API
  description: AWS Elemental MediaPackage
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mediapackage
  x-aws-signingName: mediapackage
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mediapackage-2017-10-12.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://mediapackage.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaPackage multi-region endpoint
- url: https://mediapackage.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaPackage multi-region endpoint
- url: http://mediapackage.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaPackage endpoint for China (Beijing) and China (Ningxia)
- url: https://mediapackage.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaPackage endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Channels
paths:
  /channels/{id}/configure_logs:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    put:
      operationId: ConfigureLogs
      description: Changes the Channel's properities to configure log subscription
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigureLogsResponse'
              examples:
                ConfigureLogs200Example:
                  summary: Default ConfigureLogs 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreatedAt: example-value
                    Description: Example description
                    EgressAccessLogs: example-value
                    HlsIngest: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                ConfigureLogs480Example:
                  summary: Default ConfigureLogs 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ConfigureLogs481Example:
                  summary: Default ConfigureLogs 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                ConfigureLogs482Example:
                  summary: Default ConfigureLogs 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                ConfigureLogs483Example:
                  summary: Default ConfigureLogs 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                ConfigureLogs484Example:
                  summary: Default ConfigureLogs 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                ConfigureLogs485Example:
                  summary: Default ConfigureLogs 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the channel to log subscription.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                egressAccessLogs:
                  description: Configure egress access logging.
                  type: object
                  properties:
                    LogGroupName:
                      allOf:
                      - $ref: '#/components/schemas/__string'
                      - xml:
                          name: logGroupName
                        description: Customize the log group name.
                ingressAccessLogs:
                  description: Configure ingress access logging.
                  type: object
                  properties:
                    LogGroupName:
                      allOf:
                      - $ref: '#/components/schemas/__string'
                      - xml:
                          name: logGroupName
                        description: Customize the log group name.
      summary: Amazon MediaPackage Configure Logs
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
  /channels:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateChannel
      description: Creates a new Channel.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChannelResponse'
              examples:
                CreateChannel200Example:
                  summary: Default CreateChannel 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreatedAt: example-value
                    Description: Example description
                    EgressAccessLogs: example-value
                    HlsIngest: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                CreateChannel480Example:
                  summary: Default CreateChannel 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                CreateChannel481Example:
                  summary: Default CreateChannel 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                CreateChannel482Example:
                  summary: Default CreateChannel 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                CreateChannel483Example:
                  summary: Default CreateChannel 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                CreateChannel484Example:
                  summary: Default CreateChannel 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                CreateChannel485Example:
                  summary: Default CreateChannel 485 response
                  x-microcks-default: true
                  value: {}
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - id
              properties:
                description:
                  description: A short text description of the Channel.
                  type: string
                id:
                  description: 'The ID of the Channel. The ID must be unique within the region and it

                    cannot be changed after a Channel is created.

                    '
                  type: string
                tags:
                  description: A collection of tags associated with a resource
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/__string'
      summary: Amazon MediaPackage Create Channel
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
    get:
      operationId: ListChannels
      description: Returns a collection of Channels.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListChannelsResponse'
              examples:
                ListChannels200Example:
                  summary: Default ListChannels 200 response
                  x-microcks-default: true
                  value:
                    Channels: example-value
                    NextToken: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                ListChannels480Example:
                  summary: Default ListChannels 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ListChannels481Example:
                  summary: Default ListChannels 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                ListChannels482Example:
                  summary: Default ListChannels 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                ListChannels483Example:
                  summary: Default ListChannels 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                ListChannels484Example:
                  summary: Default ListChannels 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                ListChannels485Example:
                  summary: Default ListChannels 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: maxResults
        in: query
        required: false
        description: Upper bound on number of records to return.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: nextToken
        in: query
        required: false
        description: A token used to resume pagination from the end of a previous request.
        schema:
          type: string
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon MediaPackage List Channels
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
  /channels/{id}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    delete:
      operationId: DeleteChannel
      description: Deletes an existing Channel.
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteChannelResponse'
              examples:
                DeleteChannel202Example:
                  summary: Default DeleteChannel 202 response
                  x-microcks-default: true
                  value: {}
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                DeleteChannel480Example:
                  summary: Default DeleteChannel 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                DeleteChannel481Example:
                  summary: Default DeleteChannel 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                DeleteChannel482Example:
                  summary: Default DeleteChannel 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DeleteChannel483Example:
                  summary: Default DeleteChannel 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                DeleteChannel484Example:
                  summary: Default DeleteChannel 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                DeleteChannel485Example:
                  summary: Default DeleteChannel 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the Channel to delete.
        schema:
          type: string
      summary: Amazon MediaPackage Delete Channel
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
    get:
      operationId: DescribeChannel
      description: Gets details about a Channel.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeChannelResponse'
              examples:
                DescribeChannel200Example:
                  summary: Default DescribeChannel 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreatedAt: example-value
                    Description: Example description
                    EgressAccessLogs: example-value
                    HlsIngest: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                DescribeChannel480Example:
                  summary: Default DescribeChannel 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                DescribeChannel481Example:
                  summary: Default DescribeChannel 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                DescribeChannel482Example:
                  summary: Default DescribeChannel 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DescribeChannel483Example:
                  summary: Default DescribeChannel 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                DescribeChannel484Example:
                  summary: Default DescribeChannel 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                DescribeChannel485Example:
                  summary: Default DescribeChannel 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of a Channel.
        schema:
          type: string
      summary: Amazon MediaPackage Describe Channel
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
    put:
      operationId: UpdateChannel
      description: Updates an existing Channel.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateChannelResponse'
              examples:
                UpdateChannel200Example:
                  summary: Default UpdateChannel 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreatedAt: example-value
                    Description: Example description
                    EgressAccessLogs: example-value
                    HlsIngest: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                UpdateChannel480Example:
                  summary: Default UpdateChannel 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                UpdateChannel481Example:
                  summary: Default UpdateChannel 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                UpdateChannel482Example:
                  summary: Default UpdateChannel 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                UpdateChannel483Example:
                  summary: Default UpdateChannel 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                UpdateChannel484Example:
                  summary: Default UpdateChannel 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                UpdateChannel485Example:
                  summary: Default UpdateChannel 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the Channel to update.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  description: A short text description of the Channel.
                  type: string
      summary: Amazon MediaPackage Update Channel
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
  /channels/{id}/credentials:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    put:
      deprecated: true
      operationId: RotateChannelCredentials
      description: Changes the Channel's first IngestEndpoint's username and password. WARNING - This API is deprecated. Please use RotateIngestEndpointCredentials instead
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RotateChannelCredentialsResponse'
              examples:
                RotateChannelCredentials200Example:
                  summary: Default RotateChannelCredentials 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreatedAt: example-value
                    Description: Example description
                    EgressAccessLogs: example-value
                    HlsIngest: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                RotateChannelCredentials480Example:
                  summary: Default RotateChannelCredentials 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                RotateChannelCredentials481Example:
                  summary: Default RotateChannelCredentials 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                RotateChannelCredentials482Example:
                  summary: Default RotateChannelCredentials 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                RotateChannelCredentials483Example:
                  summary: Default RotateChannelCredentials 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                RotateChannelCredentials484Example:
                  summary: Default RotateChannelCredentials 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                RotateChannelCredentials485Example:
                  summary: Default RotateChannelCredentials 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the channel to update.
        schema:
          type: string
      summary: Amazon MediaPackage Rotate Channel Credentials
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
  /channels/{id}/ingest_endpoints/{ingest_endpoint_id}/credentials:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    put:
      operationId: RotateIngestEndpointCredentials
      description: Rotate the IngestEndpoint's username and password, as specified by the IngestEndpoint's id.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RotateIngestEndpointCredentialsResponse'
              examples:
                RotateIngestEndpointCredentials200Example:
                  summary: Default RotateIngestEndpointCredentials 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreatedAt: example-value
                    Description: Example description
                    EgressAccessLogs: example-value
                    HlsIngest: example-value
        '480':
          description: UnprocessableEntityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityException'
              examples:
                RotateIngestEndpointCredentials480Example:
                  summary: Default RotateIngestEndpointCredentials 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                RotateIngestEndpointCredentials481Example:
                  summary: Default RotateIngestEndpointCredentials 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                RotateIngestEndpointCredentials482Example:
                  summary: Default RotateIngestEndpointCredentials 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                RotateIngestEndpointCredentials483Example:
                  summary: Default RotateIngestEndpointCredentials 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                RotateIngestEndpointCredentials484Example:
                  summary: Default RotateIngestEndpointCredentials 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                RotateIngestEndpointCredentials485Example:
                  summary: Default RotateIngestEndpointCredentials 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the channel the IngestEndpoint is on.
        schema:
          type: string
      - name: ingest_endpoint_id
        in: path
        required: true
        description: The id of the IngestEndpoint whose credentials should be rotated
        schema:
          type: string
      summary: Amazon MediaPackage Rotate Ingest Endpoint Credentials
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Channels
components:
  schemas:
    UpdateChannelResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
    ListChannelsResponse:
      type: object
      properties:
        Channels:
          allOf:
          - $ref: '#/components/schemas/__listOfChannel'
          - xml:
              name: channels
            description: A list of Channel records.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: nextToken
            description: A token that can be used to resume pagination from the end of the collection.
    IngestEndpoint:
      type: object
      properties:
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The system generated unique identifier for the IngestEndpoint
        Password:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: password
            description: The system generated password for ingest authentication.
        Url:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: url
            description: The ingest URL to which the source stream should be sent.
        Username:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: username
            description: The system generated username for ingest authentication.
      description: An endpoint for ingesting source content for a Channel.
    DescribeChannelResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
    ForbiddenException: {}
    TooManyRequestsException: {}
    IngressAccessLogs:
      type: object
      properties:
        LogGroupName:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: logGroupName
            description: Customize the log group name.
      description: Configure ingress access logging.
    EgressAccessLogs:
      type: object
      properties:
        LogGroupName:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: logGroupName
            description: Customize the log group name.
      description: Configure egress access logging.
    UnprocessableEntityException: {}
    __listOfChannel:
      type: array
      items:
        $ref: '#/components/schemas/Channel'
    CreateChannelResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
    Channel:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
      description: A Channel resource configuration.
    ConfigureLogsResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
    Tags:
      type: object
      description: A collection of tags associated with a resource
      additionalProperties:
        $ref: '#/components/schemas/__string'
    RotateChannelCredentialsResponse:
      deprecated: true
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
    RotateIngestEndpointCredentialsResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) assigned to the Channel.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: createdAt
            description: The date and time the Channel was created.
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: A short text description of the Channel.
        EgressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/EgressAccessLogs'
          - xml:
              name: egressAccessLogs
        HlsIngest:
          allOf:
          - $ref: '#/components/schemas/HlsIngest'
          - xml:
              name: hlsIngest
        Id:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: id
            description: The ID of the Channel.
        IngressAccessLogs:
          allOf:
          - $ref: '#/components/schemas/IngressAccessLogs'
          - xml:
              name: ingressAccessLogs
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - xml:
              name: tags
    __string:
      type: string
    InternalServerErrorException: {}
    HlsIngest:
      type: object
      properties:
        IngestEndpoints:
          allOf:
          - $ref: '#/components/schemas/__listOfIngestEndpoint'
          - xml:
              name: ingestEndpoints
            description: A list of endpoints to which the source stream should be sent.
      description: An HTTP Live Streaming (HLS) ingest resource configuration.
    NotFoundException: {}
    __listOfIngestEndpoint:
      type: array
      items:
        $ref: '#/components/schemas/IngestEndpoint'
    ServiceUnavailableException: {}
    DeleteChannelResponse:
      type: object
      properties: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mediapackage/
x-hasEquivalentPaths: true
